Add Solr config update tip
ddev/ddev-drupal9-solr pull request #27
Opened 2023-06-12 17:51 UTC by gitressa

## The Issue
Solves #15.

## How This PR Solves The Issue

Adds documentation on how to fix outdated Solr config files message.

Also updates the "Alternate Core Name" section, the first step (`1. Remove the #ddev-generated at the top of the file.`) isn't necessary, it seems?

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2023-06-12 17:57 UTC, rfay requested changes
It all looks great, just the one question about why you removed #ddev-generated notice.

2023-06-12 17:57 UTC, rfay commented on README.md
> -1. Remove the #ddev-generated at the top of the file.
Why did you remove the first item here?

2023-06-12 17:58 UTC, rfay commented
If you don't remove the `#ddev-generated` then the file will be recreated with the default file on `ddev restart`.

2023-06-12 18:26 UTC, gitressa commented
I removed it because after creating the file _.ddev/docker-compose.solr-env.yaml_, adding this:

```
services:
  solr:
    environment:
    - SOLR_CORENAME=somecorename
```

and restarting DDEV. At no point do I see a line saying `#ddev-generated`, so I removed that first line ...

Or is that first line about something else?

2023-06-12 19:12 UTC, rfay approved these changes

2023-06-12 19:12 UTC, rfay commented on README.md
> -1. Remove the #ddev-generated at the top of the file.
Ah, I didn't see the context `If you want to use a core name other than the default "dev", add a .ddev/docker-compose.solr-env.yaml with these contents, using the core name you want to use:`, thought it was referring to docker-compose.solr.yaml.

2023-06-12 19:12 UTC, merged

2023-06-12 20:10 UTC, gitressa commented
Great, thanks!

2023-06-12 20:38 UTC, rfay commented
Thanks for the contribution and for keeping your eye on this repo. You know and use solr far more than I do, and it needs knowledgable folks following it.

2023-06-13 17:42 UTC, gitressa commented
You're welcome, I am glad I could help. It's a privilege to assist you with DDEV, it's an amazing web developer tool.