Added verbose instructions for Solr 7 and Drupal 7
ddev/ddev-drupal9-solr pull request #45
Opened 2024-12-13 21:46 UTC by jenlampton

## The Issue

README only includes docs for Drupal 9+

## How This PR Solves The Issue

Adds legacy instructions for Drupal 7

## Manual Testing Instructions

N/A

## Automated Testing Overview

N/A

## Related Issue Link(s)

https://github.com/ddev/ddev-drupal-solr/issues/44#issuecomment-2540285944

## Release/Deployment Notes

> Does this affect anything else or have ramifications for other code? Does anything have to be done on deployment?

Nope :)

2024-12-24 15:49 UTC, rfay requested changes
Thanks so much for developing your expertise on this and contributing it back. I'm sorry I'm slow to respond, was hoping for another review, but this will be super helpful to people with just a little adjustment, mostly using `docker-compose.solr_extra.yaml` instead of editing the original file.

2024-12-24 15:49 UTC, rfay commented on README.md
> +2. Set the version of Solr verison 7: Edit the `.ddev/docker-compose.solr.yaml` file. Replace `image: solr:8` with `image: solr:7` on line 34.
```suggestion
2. Set the version of Solr version 7: Edit the `.ddev/docker-compose.solr.yaml` file. Replace `image: solr:8` with `image: solr:7` on line 34.
```

2024-12-24 15:49 UTC, rfay commented on README.md
> +6. If the Ddev drush version is too new for Drupal 7, you may need to symlink `drush` to the `drush8` provided with Ddev. You can do this by adding a `post-start` hook inside your `.ddev/config.yaml`
I don't really understand this. If a project is configured with project type `drupal7` (or `backdrop` I think) then `drush` is already `drush8`, so why would one need to do this? Using project type `php` ?

2024-12-24 15:49 UTC, rfay commented on README.md
> +2. Set the version of Solr verison 7: Edit the `.ddev/docker-compose.solr.yaml` file. Replace `image: solr:8` with `image: solr:7` on line 34.
Rather than editing the `.ddev/docker-compose-solr.yaml` it's best practice to use a `.ddev/docker-compose-solr_extras.yaml` to override the value (in your case, it would seem to need only:

```yaml
services:
  solr:
     image: solr: 7
```

 That way a `ddev add-on get` won't overwrite your work. Also, if you *did* edit the way you say here, the `docker-compose.solr.yaml` would have to have the `#ddev-generated` line removed from it, or it would be overwritten.

2025-02-11 17:22 UTC, rfay commented
I'd like to get this in, so would love it if you could return to this @jenlampton , thanks!

2025-04-24 11:32 UTC, stasadev commented
Rebased.

2025-04-24 11:34 UTC, stasadev commented
> this will be super helpful to people with just a little adjustment, mostly using `docker-compose.solr_extra.yaml` instead of editing the original file. 

@jenlampton, README.md already has some mentions for `docker-compose.solr_extra.yaml`, so it should be easier to refactor.

2025-11-14 14:55 UTC, rfay approved these changes
I guess people must think it's good enough.

2025-11-14 14:55 UTC, merged